[vmovie]
title = "V MOVIE"
url = "https://www.vlive.tv/channel/FA1A3/board/3641?lang=ko"
entrySelector = "li[class^='post_item']"
titleSelector = "strong[class^='title_text']"
linkSelector = "a[class^='post_area']"
imageSelector = "span[class^='covered_image']"
contentSelector = "span[class^='upload_time']"
waitForSelector = "li[class^='post_item']"
onFail = "stale"

[vmovie_notice]
title = "V MOVIE - Notice"
url = "https://www.vlive.tv/channel/FA1A3/board/171"
entrySelector = "li[class^='post_item']"
titleSelector = "strong[class^='title_text']"
linkSelector = "a[class^='post_area']"
imageSelector = "span[class^='covered_image']"
contentSelector = "span[class^='upload_time']"
waitUntil = "networkidle"
onFail = "stale"

[vscreen]
title = "V SCREEN"
url = "https://www.vlive.tv/channel/C956BB/board/5167?lang=ko"
entrySelector = "li[class^='post_item']"
titleSelector = "strong[class^='title_text']"
linkSelector = "a[class^='post_area']"
imageSelector = "span[class^='covered_image']"
contentSelector = "span[class^='upload_time']"
waitForSelector = "li[class^='post_item']"
onFail = "stale"

[vscreen_notice]
title = "V SCREEN"
url = "https://www.vlive.tv/channel/C956BB/board/1732"
entrySelector = "li[class^='post_item']"
titleSelector = "strong[class^='title_text']"
linkSelector = "a[class^='post_area']"
imageSelector = "span[class^='covered_image']"
contentSelector = "span[class^='upload_time']"
waitUntil = "networkidle"
onFail = "stale"
